[package]
name = "actix-web-sample"
version = "0.1.0"
authors = ["susiyaki <susiyaki.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
